language: python
sudo: false
cache: pip

python:
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -U pylama
  - pip install -U -r requirements.txt

script:
  - pylama .